// PaperTrack — Baked Paper Templates
// To add a paper, paste the DeepSeek output below the relevant section comment.
// Format: BAKED_TEMPLATES['subject']['Paper X'][year] = [ ...questions... ];

const BAKED_TEMPLATES = {
  maths:   { 'Paper 1': {}, 'Paper 2': {}, 'Paper 3': {} },
  physics: { 'Paper 1': {}, 'Paper 2': {}, 'Paper 3': {} },
  cs:      { 'Paper 1': {}, 'Paper 2': {} },
};

// ── Physics › Paper 1 ────────────────────────────────────────────────────────

BAKED_TEMPLATES['physics']['Paper 1'][2017] = [
  { n:1, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 }] },
  { n:2, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:3, topic:'Work, Energy & Power', subtopic:'', parts:[{ l:'', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:1 }] },
  { n:4, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:5, topic:'Practical Skills & Data Analysis', subtopic:'', parts:[{ l:'', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:1 }] },
  { n:6, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:7, topic:'Quantum Physics & Photoelectric Effect', subtopic:'', parts:[{ l:'', topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect'], subtopic:'', marks:1 }] },
  { n:8, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:9, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 }] },
  { n:10, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:11, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:12, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:13, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:14, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:15, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:16, topic:'Work, Energy & Power', subtopic:'', parts:[
    { l:'a', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'c', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
  ]},
  { n:17, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',   topic:'Thermal Physics', topics:['Thermal Physics', 'Practical Skills & Data Analysis'], subtopic:'', marks:2 },
    { l:'b i', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:1 },
    { l:'b ii',topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:2 },
    { l:'c i', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:1 },
    { l:'c ii',topic:'Thermal Physics', topics:['Thermal Physics', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
    { l:'d',   topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:2 },
    { l:'e',   topic:'Thermal Physics', topics:['Thermal Physics', 'Practical Skills & Data Analysis'], subtopic:'', marks:4 },
  ]},
  { n:18, topic:'Forces in Action', subtopic:'', parts:[
    { l:'a i',  topic:'Materials', topics:['Materials'], subtopic:'', marks:2 },
    { l:'a ii', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b',    topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'c i',  topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:3 },
    { l:'c ii', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:3 },
    { l:'d',    topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:2 },
  ]},
  { n:19, topic:'Oscillations (SHM)', subtopic:'', parts:[
    { l:'a i',  topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:3 },
    { l:'a ii', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
    { l:'b',    topic:'Oscillations (SHM)', topics:['Oscillations (SHM)', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
    { l:'c i',  topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
    { l:'c ii', topic:'Oscillations (SHM)', topics:['Gravitational Fields', 'Oscillations (SHM)'], subtopic:'', marks:2 },
  ]},
  { n:20, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:4 },
  ]},
  { n:21, topic:'Quantum Physics & Photoelectric Effect', subtopic:'', parts:[
    { l:'a i',    topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect'], subtopic:'', marks:1 },
    { l:'a ii 1', topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect'], subtopic:'', marks:1 },
    { l:'a ii 2', topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect'], subtopic:'', marks:3 },
    { l:'b i',    topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect'], subtopic:'', marks:1 },
    { l:'b ii',   topic:'Waves', topics:['Waves'], subtopic:'', marks:1 },
    { l:'b iii',  topic:'Waves', topics:['Waves'], subtopic:'', marks:3 },
    { l:'b iv',   topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'c',      topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
  ]},
  { n:22, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'b', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:4 },
  ]},
  { n:23, topic:'Gravitational Fields', subtopic:'', parts:[
    { l:'a',    topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
    { l:'b i',  topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
    { l:'b iii',topic:'Gravitational Fields', topics:['Gravitational Fields', 'Thermal Physics'], subtopic:'', marks:3 },
  ]},
];

BAKED_TEMPLATES['physics']['Paper 1'][2018] = [
  { n:1, topic:'Electric Circuits', subtopic:'', parts:[{ l:'', topic:'Electric Circuits', topics:['Electric Circuits'], subtopic:'', marks:1 }] },
  { n:2, topic:'Electric Circuits', subtopic:'', parts:[{ l:'', topic:'Electric Circuits', topics:['Electric Circuits'], subtopic:'', marks:1 }] },
  { n:3, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:4, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:5, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:6, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:7, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:8, topic:'Quantum Physics & Photoelectric Effect', subtopic:'', parts:[{ l:'', topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect'], subtopic:'', marks:1 }] },
  { n:9, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:10, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:11, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:12, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:13, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 }] },
  { n:14, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:15, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:16, topic:'Motion (Kinematics)', subtopic:'', parts:[
    { l:'a i',   topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 },
    { l:'a ii',  topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'a iii', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:1 },
    { l:'a iv',  topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b',     topic:'Motion (Kinematics)', topics:['Motion (Kinematics)', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:17, topic:'Gravitational Fields', subtopic:'', parts:[
    { l:'a i',    topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
    { l:'a ii',   topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:2 },
    { l:'a iii',  topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:3 },
    { l:'b i',    topic:'Gravitational Fields', topics:['Gravitational Fields', 'Practical Skills & Data Analysis'], subtopic:'', marks:1 },
    { l:'b ii 1', topic:'Gravitational Fields', topics:['Gravitational Fields', 'Practical Skills & Data Analysis'], subtopic:'', marks:2 },
    { l:'b ii 2', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
    { l:'b ii 3', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:2 },
    { l:'c i',    topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:2 },
    { l:'c ii',   topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:2 },
  ]},
  { n:18, topic:'Work, Energy & Power', subtopic:'', parts:[
    { l:'a',    topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b i',  topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:3 },
    { l:'b ii', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b iii',topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
  ]},
  { n:19, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'b i',  topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect', 'Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
  ]},
  { n:20, topic:'Work, Energy & Power', subtopic:'', parts:[
    { l:'a',      topic:'Work, Energy & Power', topics:['Work, Energy & Power', 'Forces in Action'], subtopic:'', marks:2 },
    { l:'b i',    topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:3 },
    { l:'b ii',   topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b iii 1',topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'b iii 2',topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
  ]},
  { n:21, topic:'Circular Motion', subtopic:'', parts:[
    { l:'a', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b', topic:'Circular Motion', topics:['Circular Motion', 'Practical Skills & Data Analysis'], subtopic:'', marks:3 },
    { l:'c', topic:'Circular Motion', topics:['Circular Motion'], subtopic:'', marks:3 },
  ]},
  { n:22, topic:'Nuclear & Particle Physics', subtopic:'', parts:[
    { l:'a i',  topic:'Nuclear & Particle Physics', topics:['Forces in Action', 'Nuclear & Particle Physics'], subtopic:'', marks:1 },
    { l:'a ii', topic:'Nuclear & Particle Physics', topics:['Forces in Action', 'Nuclear & Particle Physics'], subtopic:'', marks:3 },
    { l:'b',    topic:'Nuclear & Particle Physics', topics:['Thermal Physics', 'Gravitational Fields', 'Nuclear & Particle Physics', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:23, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'b i',  topic:'Waves', topics:['Thermal Physics', 'Waves'], subtopic:'', marks:3 },
    { l:'b ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'c',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:4 },
  ]},
  { n:24, topic:'Waves', subtopic:'', parts:[
    { l:'a',    topic:'Waves', topics:['Waves'], subtopic:'', marks:1 },
    { l:'b i',  topic:'Waves', topics:['Waves', 'Practical Skills & Data Analysis'], subtopic:'', marks:3 },
    { l:'b ii', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:1 },
    { l:'b iii',topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:1 },
  ]},
];

BAKED_TEMPLATES['physics']['Paper 1'][2019] = [
  { n:1, topic:'Scalars & Vectors', subtopic:'', parts:[{ l:'', topic:'Scalars & Vectors', topics:['Scalars & Vectors'], subtopic:'', marks:1 }] },
  { n:2, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:3, topic:'Practical Skills & Data Analysis', subtopic:'', parts:[{ l:'', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:1 }] },
  { n:4, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:5, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:6, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 }] },
  { n:7, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:8, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:9, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:10, topic:'Scalars & Vectors', subtopic:'', parts:[{ l:'', topic:'Scalars & Vectors', topics:['Scalars & Vectors'], subtopic:'', marks:1 }] },
  { n:11, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 }] },
  { n:12, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:13, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:14, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:15, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:16, topic:'Materials', subtopic:'', parts:[
    { l:'a',    topic:'Materials', topics:['Materials'], subtopic:'', marks:1 },
    { l:'b i',  topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Materials', topics:['Materials'], subtopic:'', marks:2 },
    { l:'b iii',topic:'Materials', topics:['Materials'], subtopic:'', marks:2 },
    { l:'c',    topic:'Materials', topics:['Materials'], subtopic:'', marks:2 },
    { l:'d',    topic:'Materials', topics:['Materials', 'Work, Energy & Power'], subtopic:'', marks:2 },
  ]},
  { n:17, topic:'Forces in Action', subtopic:'', parts:[
    { l:'a',    topic:'Motion (Kinematics)', topics:['Motion (Kinematics)', 'Practical Skills & Data Analysis'], subtopic:'', marks:3 },
    { l:'b',    topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
    { l:'c',    topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:3 },
    { l:'d i',  topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'d ii', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
  ]},
  { n:18, topic:'Oscillations (SHM)', subtopic:'', parts:[
    { l:'a i',   topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:3 },
    { l:'a ii',  topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
    { l:'b',     topic:'Oscillations (SHM)', topics:['Oscillations (SHM)', 'Work, Energy & Power'], subtopic:'', marks:4 },
    { l:'c i',   topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
    { l:'c ii',  topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 },
    { l:'c iii', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
  ]},
  { n:19, topic:'Motion (Kinematics)', subtopic:'', parts:[
    { l:'a', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:3 },
    { l:'b', topic:'Work, Energy & Power', topics:['Work, Energy & Power', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:20, topic:'Forces in Action', subtopic:'', parts:[
    { l:'a', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b', topic:'Forces in Action', topics:['Forces in Action', 'Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'c', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
  ]},
  { n:21, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:4 },
    { l:'b',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'c',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'d i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'d ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
  ]},
  { n:22, topic:'Forces in Action', subtopic:'', parts:[
    { l:'a', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
    { l:'b', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:3 },
  ]},
  { n:23, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',    topic:'Thermal Physics', topics:['Thermal Physics', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
    { l:'b i',  topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:1 },
    { l:'b ii', topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:2 },
  ]},
  { n:24, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a i',   topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'a ii',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b i',   topic:'Gravitational Fields', topics:['Gravitational Fields', 'Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'b iii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
  ]},
];

BAKED_TEMPLATES['physics']['Paper 1'][2020] = [
  { n:1, topic:'Work, Energy & Power', subtopic:'', parts:[{ l:'', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:1 }] },
  { n:2, topic:'Scalars & Vectors', subtopic:'', parts:[{ l:'', topic:'Scalars & Vectors', topics:['Scalars & Vectors'], subtopic:'', marks:1 }] },
  { n:3, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:4, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:5, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 }] },
  { n:6, topic:'Quantum Physics & Photoelectric Effect', subtopic:'', parts:[{ l:'', topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect'], subtopic:'', marks:1 }] },
  { n:7, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:8, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:9, topic:'Waves', subtopic:'', parts:[{ l:'', topic:'Waves', topics:['Waves'], subtopic:'', marks:1 }] },
  { n:10, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:11, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:12, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:13, topic:'Practical Skills & Data Analysis', subtopic:'', parts:[{ l:'', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis', 'Materials'], subtopic:'', marks:1 }] },
  { n:14, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:15, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:16, topic:'Work, Energy & Power', subtopic:'', parts:[
    { l:'a', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
    { l:'c', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
    { l:'d', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:3 },
    { l:'e', topic:'Materials', topics:['Materials'], subtopic:'', marks:3 },
  ]},
  { n:17, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'a ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'b',    topic:'Thermal Physics', topics:['Thermal Physics', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:18, topic:'Motion (Kinematics)', subtopic:'', parts:[
    { l:'a',    topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b',    topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'c',    topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:3 },
    { l:'d i',  topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
    { l:'d ii', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
  ]},
  { n:19, topic:'Forces in Action', subtopic:'', parts:[
    { l:'', topic:'Forces in Action', topics:['Forces in Action', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:20, topic:'Circular Motion', subtopic:'', parts:[
    { l:'a', topic:'Circular Motion', topics:['Circular Motion'], subtopic:'', marks:3 },
    { l:'b', topic:'Circular Motion', topics:['Circular Motion', 'Practical Skills & Data Analysis'], subtopic:'', marks:4 },
  ]},
  { n:21, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a i',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'a ii',   topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b i',    topic:'Forces in Action', topics:['Forces in Action', 'Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii 1', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 },
    { l:'b ii 2', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b iii',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
  ]},
  { n:22, topic:'Forces in Action', subtopic:'', parts:[
    { l:'a i',  topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
    { l:'a ii', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b i',  topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:3 },
    { l:'b ii', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
    { l:'b iii',topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
  ]},
  { n:23, topic:'Gravitational Fields', subtopic:'', parts:[
    { l:'a i',   topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:1 },
    { l:'a ii',  topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:2 },
    { l:'b i',   topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
    { l:'b ii',  topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
    { l:'b iii', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:2 },
    { l:'c',     topic:'Gravitational Fields', topics:['Gravitational Fields', 'Work, Energy & Power'], subtopic:'', marks:3 },
  ]},
  { n:24, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:4 },
    { l:'b i',  topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect', 'Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'c',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
  ]},
];

BAKED_TEMPLATES['physics']['Paper 1'][2021] = [
  { n:1, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:2, topic:'Scalars & Vectors', subtopic:'', parts:[{ l:'', topic:'Scalars & Vectors', topics:['Scalars & Vectors'], subtopic:'', marks:1 }] },
  { n:3, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:4, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:5, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:6, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:7, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 }] },
  { n:8, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:9, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:10, topic:'Work, Energy & Power', subtopic:'', parts:[{ l:'', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:1 }] },
  { n:11, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:1 }] },
  { n:12, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:13, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:14, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:15, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:16, topic:'Motion (Kinematics)', subtopic:'', parts:[
    { l:'a i',   topic:'Motion (Kinematics)', topics:['Scalars & Vectors', 'Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'a ii',  topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:4 },
    { l:'b i',   topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
    { l:'b ii',  topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:3 },
    { l:'b iii', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
  ]},
  { n:17, topic:'Materials', subtopic:'', parts:[
    { l:'a', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:3 },
    { l:'b', topic:'Materials', topics:['Materials', 'Oscillations (SHM)', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:18, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a i',   topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'a ii',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'a iii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b i',   topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'b iii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
  ]},
  { n:19, topic:'Forces in Action', subtopic:'', parts:[
    { l:'a',    topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
    { l:'b i',  topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:3 },
    { l:'b ii', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'c',    topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
  ]},
  { n:20, topic:'Gravitational Fields', subtopic:'', parts:[
    { l:'a i',  topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
    { l:'a ii', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
    { l:'b',    topic:'Gravitational Fields', topics:['Gravitational Fields', 'Work, Energy & Power', 'Circular Motion'], subtopic:'', marks:6 },
  ]},
  { n:21, topic:'Oscillations (SHM)', subtopic:'', parts:[
    { l:'a',      topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:4 },
    { l:'b i',    topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:3 },
    { l:'b ii 1', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'b ii 2', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
  ]},
  { n:22, topic:'Circular Motion', subtopic:'', parts:[
    { l:'a i',   topic:'Circular Motion', topics:['Circular Motion', 'Scalars & Vectors'], subtopic:'', marks:2 },
    { l:'a ii',  topic:'Circular Motion', topics:['Circular Motion', 'Practical Skills & Data Analysis'], subtopic:'', marks:3 },
    { l:'a iii', topic:'Circular Motion', topics:['Circular Motion', 'Forces in Action'], subtopic:'', marks:3 },
    { l:'b',     topic:'Circular Motion', topics:['Circular Motion'], subtopic:'', marks:2 },
  ]},
  { n:23, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',     topic:'Gravitational Fields', topics:['Gravitational Fields', 'Practical Skills & Data Analysis'], subtopic:'', marks:4 },
    { l:'b i',   topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'b ii',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b iii', topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect', 'Thermal Physics'], subtopic:'', marks:2 },
    { l:'b iv',  topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect', 'Thermal Physics'], subtopic:'', marks:1 },
    { l:'b v',   topic:'Waves', topics:['Quantum Physics & Photoelectric Effect', 'Waves'], subtopic:'', marks:3 },
    { l:'c',     topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
  ]},
];

BAKED_TEMPLATES['physics']['Paper 1'][2022] = [
  { n:1, topic:'Scalars & Vectors', subtopic:'', parts:[{ l:'', topic:'Scalars & Vectors', topics:['Scalars & Vectors'], subtopic:'', marks:1 }] },
  { n:2, topic:'Practical Skills & Data Analysis', subtopic:'', parts:[{ l:'', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:1 }] },
  { n:3, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:4, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:5, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:6, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:7, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:8, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:9, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:10, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:11, topic:'Scalars & Vectors', subtopic:'', parts:[{ l:'', topic:'Scalars & Vectors', topics:['Scalars & Vectors'], subtopic:'', marks:1 }] },
  { n:12, topic:'Quantum Physics & Photoelectric Effect', subtopic:'', parts:[{ l:'', topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect'], subtopic:'', marks:1 }] },
  { n:13, topic:'Waves', subtopic:'', parts:[{ l:'', topic:'Waves', topics:['Waves'], subtopic:'', marks:1 }] },
  { n:14, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:15, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:16, topic:'Materials', subtopic:'', parts:[
    { l:'a',    topic:'Materials', topics:['Materials', 'Practical Skills & Data Analysis'], subtopic:'', marks:4 },
    { l:'b i',  topic:'Materials', topics:['Materials', 'Work, Energy & Power'], subtopic:'', marks:3 },
    { l:'b ii', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b iii',topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:3 },
    { l:'b iv', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:2 },
  ]},
  { n:17, topic:'Work, Energy & Power', subtopic:'', parts:[
    { l:'a', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:1 },
    { l:'b', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:3 },
    { l:'c', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)', 'Forces in Action'], subtopic:'', marks:4 },
  ]},
  { n:18, topic:'Forces in Action', subtopic:'', parts:[
    { l:'a i',  topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:3 },
    { l:'a ii', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b',    topic:'Forces in Action', topics:['Forces in Action', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:19, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'b ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'b iii',topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'b iv', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:4 },
  ]},
  { n:20, topic:'Oscillations (SHM)', subtopic:'', parts:[
    { l:'a',      topic:'Oscillations (SHM)', topics:['Oscillations (SHM)', 'Scalars & Vectors'], subtopic:'', marks:2 },
    { l:'b i',    topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
    { l:'b ii 1', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:3 },
    { l:'b ii 2', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:3 },
    { l:'b ii 3', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
  ]},
  { n:21, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'b i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'c i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'c ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:4 },
  ]},
  { n:22, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a', topic:'Thermal Physics', topics:['Thermal Physics', 'Practical Skills & Data Analysis'], subtopic:'', marks:2 },
    { l:'b', topic:'Nuclear & Particle Physics', topics:['Thermal Physics', 'Nuclear & Particle Physics'], subtopic:'', marks:6 },
  ]},
  { n:23, topic:'Gravitational Fields', subtopic:'', parts:[
    { l:'a',    topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:3 },
    { l:'b i',  topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Gravitational Fields', topics:['Gravitational Fields', 'Work, Energy & Power'], subtopic:'', marks:3 },
    { l:'b iii',topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
  ]},
];

BAKED_TEMPLATES['physics']['Paper 1'][2023] = [
  { n:1, topic:'Scalars & Vectors', subtopic:'', parts:[{ l:'', topic:'Scalars & Vectors', topics:['Scalars & Vectors'], subtopic:'', marks:1 }] },
  { n:2, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:3, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:4, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:5, topic:'Materials', subtopic:'', parts:[{ l:'', topic:'Materials', topics:['Materials'], subtopic:'', marks:1 }] },
  { n:6, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:7, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 }] },
  { n:8, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:9, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:10, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:11, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:1 }] },
  { n:12, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:13, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:14, topic:'Waves', subtopic:'', parts:[{ l:'', topic:'Waves', topics:['Thermal Physics', 'Waves'], subtopic:'', marks:1 }] },
  { n:15, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:16, topic:'Motion (Kinematics)', subtopic:'', parts:[
    { l:'a i',   topic:'Motion (Kinematics)', topics:['Motion (Kinematics)', 'Scalars & Vectors'], subtopic:'', marks:2 },
    { l:'a ii',  topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 },
    { l:'a iii', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:3 },
    { l:'b i',   topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b ii',  topic:'Work, Energy & Power', topics:['Work, Energy & Power', 'Forces in Action'], subtopic:'', marks:2 },
  ]},
  { n:17, topic:'Circular Motion', subtopic:'', parts:[
    { l:'a i',   topic:'Circular Motion', topics:['Circular Motion'], subtopic:'', marks:1 },
    { l:'a ii',  topic:'Circular Motion', topics:['Circular Motion'], subtopic:'', marks:2 },
    { l:'a iii', topic:'Circular Motion', topics:['Circular Motion'], subtopic:'', marks:3 },
    { l:'a iv',  topic:'Circular Motion', topics:['Circular Motion'], subtopic:'', marks:2 },
    { l:'b i',   topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'b ii',  topic:'Circular Motion', topics:['Circular Motion', 'Motion (Kinematics)'], subtopic:'', marks:3 },
    { l:'b iii', topic:'Forces in Action', topics:['Forces in Action', 'Practical Skills & Data Analysis'], subtopic:'', marks:3 },
  ]},
  { n:18, topic:'Practical Skills & Data Analysis', subtopic:'', parts:[
    { l:'', topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis', 'Motion (Kinematics)'], subtopic:'', marks:6 },
  ]},
  { n:19, topic:'Forces in Action', subtopic:'', parts:[
    { l:'a',    topic:'Forces in Action', topics:['Forces in Action', 'Practical Skills & Data Analysis'], subtopic:'', marks:3 },
    { l:'b i',  topic:'Work, Energy & Power', topics:['Work, Energy & Power', 'Forces in Action'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:1 },
  ]},
  { n:20, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a',    topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'b i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'b ii', topic:'Thermal Physics', topics:['Forces in Action', 'Thermal Physics'], subtopic:'', marks:2 },
    { l:'b iii',topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b iv', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'c',    topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'d',    topic:'Work, Energy & Power', topics:['Forces in Action', 'Work, Energy & Power'], subtopic:'', marks:2 },
  ]},
  { n:21, topic:'Oscillations (SHM)', subtopic:'', parts:[
    { l:'a i',   topic:'Oscillations (SHM)', topics:['Oscillations (SHM)', 'Scalars & Vectors'], subtopic:'', marks:2 },
    { l:'a ii',  topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
    { l:'a iii', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:2 },
    { l:'b i',   topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:2 },
    { l:'b ii',  topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:2 },
    { l:'b iii', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:3 },
    { l:'c',     topic:'Oscillations (SHM)', topics:['Oscillations (SHM)', 'Work, Energy & Power'], subtopic:'', marks:4 },
  ]},
  { n:22, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'', topic:'Thermal Physics', topics:['Thermal Physics', 'Quantum Physics & Photoelectric Effect', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:23, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a i',   topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'a ii',  topic:'Thermal Physics', topics:['Thermal Physics', 'Practical Skills & Data Analysis'], subtopic:'', marks:2 },
    { l:'b i',   topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii',  topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 },
    { l:'b iii', topic:'Gravitational Fields', topics:['Gravitational Fields', 'Work, Energy & Power'], subtopic:'', marks:3 },
    { l:'b iv',  topic:'Thermal Physics', topics:['Thermal Physics', 'Gravitational Fields'], subtopic:'', marks:1 },
  ]},
];

BAKED_TEMPLATES['physics']['Paper 1'][2024] = [
  { n:1, topic:'Scalars & Vectors', subtopic:'', parts:[{ l:'', topic:'Scalars & Vectors', topics:['Scalars & Vectors'], subtopic:'', marks:1 }] },
  { n:2, topic:'Scalars & Vectors', subtopic:'', parts:[{ l:'', topic:'Scalars & Vectors', topics:['Scalars & Vectors'], subtopic:'', marks:1 }] },
  { n:3, topic:'Circular Motion', subtopic:'', parts:[{ l:'', topic:'Circular Motion', topics:['Circular Motion'], subtopic:'', marks:1 }] },
  { n:4, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:5, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:6, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:7, topic:'Motion (Kinematics)', subtopic:'', parts:[{ l:'', topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:1 }] },
  { n:8, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:9, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:10, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:11, topic:'Circular Motion', subtopic:'', parts:[{ l:'', topic:'Circular Motion', topics:['Circular Motion'], subtopic:'', marks:1 }] },
  { n:12, topic:'Oscillations (SHM)', subtopic:'', parts:[{ l:'', topic:'Oscillations (SHM)', topics:['Oscillations (SHM)'], subtopic:'', marks:1 }] },
  { n:13, topic:'Forces in Action', subtopic:'', parts:[{ l:'', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 }] },
  { n:14, topic:'Gravitational Fields', subtopic:'', parts:[{ l:'', topic:'Gravitational Fields', topics:['Gravitational Fields'], subtopic:'', marks:1 }] },
  { n:15, topic:'Thermal Physics', subtopic:'', parts:[{ l:'', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 }] },
  { n:16, topic:'Work, Energy & Power', subtopic:'', parts:[
    { l:'a i',   topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'a ii',  topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'a iii', topic:'Work, Energy & Power', topics:['Work, Energy & Power', 'Forces in Action'], subtopic:'', marks:3 },
    { l:'b',     topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:3 },
    { l:'c',     topic:'Work, Energy & Power', topics:['Work, Energy & Power'], subtopic:'', marks:2 },
  ]},
  { n:17, topic:'Forces in Action', subtopic:'', parts:[
    { l:'a',    topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:1 },
    { l:'b i',  topic:'Motion (Kinematics)', topics:['Motion (Kinematics)'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:2 },
    { l:'b iii',topic:'Forces in Action', topics:['Forces in Action'], subtopic:'', marks:3 },
  ]},
  { n:18, topic:'Materials', subtopic:'', parts:[
    { l:'a i',    topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:1 },
    { l:'a ii',   topic:'Materials', topics:['Materials', 'Practical Skills & Data Analysis'], subtopic:'', marks:3 },
    { l:'a iii',  topic:'Materials', topics:['Materials'], subtopic:'', marks:2 },
    { l:'a iv 1', topic:'Work, Energy & Power', topics:['Work, Energy & Power', 'Scalars & Vectors'], subtopic:'', marks:1 },
    { l:'a iv 2', topic:'Materials', topics:['Materials', 'Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b',      topic:'Practical Skills & Data Analysis', topics:['Practical Skills & Data Analysis'], subtopic:'', marks:2 },
  ]},
  { n:19, topic:'Waves', subtopic:'', parts:[
    { l:'', topic:'Waves', topics:['Waves', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:20, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
    { l:'a ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'c i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'c ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
  ]},
  { n:21, topic:'Thermal Physics', subtopic:'', parts:[
    { l:'a i',  topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect', 'Thermal Physics'], subtopic:'', marks:2 },
    { l:'a ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:3 },
    { l:'b i',  topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:4 },
    { l:'c',    topic:'Thermal Physics', topics:['Thermal Physics', 'Practical Skills & Data Analysis'], subtopic:'', marks:3 },
  ]},
  { n:22, topic:'Gravitational Fields', subtopic:'', parts:[
    { l:'a i',  topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:1 },
    { l:'a ii', topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion'], subtopic:'', marks:3 },
    { l:'b i',  topic:'Gravitational Fields', topics:['Gravitational Fields', 'Circular Motion', 'Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Gravitational Fields', topics:['Gravitational Fields', 'Work, Energy & Power'], subtopic:'', marks:2 },
    { l:'c',    topic:'Gravitational Fields', topics:['Work, Energy & Power', 'Gravitational Fields', 'Practical Skills & Data Analysis'], subtopic:'', marks:6 },
  ]},
  { n:23, topic:'Quantum Physics & Photoelectric Effect', subtopic:'', parts:[
    { l:'a',    topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect'], subtopic:'', marks:2 },
    { l:'b i',  topic:'Quantum Physics & Photoelectric Effect', topics:['Quantum Physics & Photoelectric Effect', 'Thermal Physics'], subtopic:'', marks:2 },
    { l:'b ii', topic:'Waves', topics:['Thermal Physics', 'Waves'], subtopic:'', marks:2 },
    { l:'b iii',topic:'Thermal Physics', topics:['Thermal Physics'], subtopic:'', marks:1 },
  ]},
];

// ── Physics › Paper 2 ────────────────────────────────────────────────────────


// ── Physics › Paper 3 ────────────────────────────────────────────────────────


// ── Maths › Paper 1 ──────────────────────────────────────────────────────────


// ── Maths › Paper 2 ──────────────────────────────────────────────────────────


// ── Maths › Paper 3 ──────────────────────────────────────────────────────────


// ── Computer Science › Paper 1 ───────────────────────────────────────────────


// ── Computer Science › Paper 2 ───────────────────────────────────────────────
